version: "3"

services:

  app:
    build:
      context: ./app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080"
    environment:
      ETH_NODE_HOST: ganache

  ganache:
    build:
      context: ./ganache
    ports:
      - "8545"
