version: "3"

services:

  app:
    build:
      context: ./app
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/build
    ports:
      - "8080:8080"
    environment:
      ETH_NODE_HOST: ganache
    command: bash ./scripts/dev_server.sh

  ganache:
    build:
      context: ./ganache
    expose:
      - "8545"
