export const CREATE_AGREEMENT_PENDING = 'CREATE_AGREEMENT_PENDING';
export const CREATE_AGREEMENT_FULFILLED = 'CREATE_AGREEMENT_FULFILLED';
export const CREATE_AGREEMENT_FAILED = 'CREATE_AGREEMENT_FAILED';
